workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never # Skip pipeline for tags
    - if: $CI_COMMIT_BRANCH
      when: always # Run pipeline for all branches

stages:
  - html:validate
  - page:deploy
  
html:vnu:
  stage: html:validate
  image: cyb3rjak3/html5validator:latest
  script:
    - html5validator --root $CI_PROJECT_DIR/public
  allow_failure: true

page:deploy:
  stage: page:deploy
  script:
  - echo "Pages accessible through ${CI_PAGES_URL}"
  artifacts:
    paths:
    - public
